# Generated by Django 5.0.6 on 2024-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_category_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('RENTED', 'Арендован'), ('RETURNED', 'Возвращено')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
