# Generated by Django 5.0.6 on 2024-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_equipmentorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentorder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('RENTED', 'Арендован'), ('RETURNED', 'Возвращено')], default=('RENTED', 'Арендован'), max_length=10),
        ),
    ]
